name: github-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Website
        uses: quarkiverse/quarkus-roq@v1
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}   # Used to automatically get the GitHub Pages url
 
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Read search configuration
        id: config
        run: echo ::set-output name=config::$(cat algolia-config.json)

      - name: Update search index
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          file: 'algolia-config.json'